### ISSUE TITLE
Làm giao diện Up Rank - Thuê người cày

### ISSUE THREAD

**Issue by TaQuangKhoi** [TaQuangKhoi/Bao-Cao-Web-3#1]
https://boostroyal.com/lol-boosting/

Step 1: Clone project, create git branch for yourself
Step 2: You can create new app to make the UI

# Expectation
![image](https://github.com/TaQuangKhoi/Bao-Cao-Web-3/assets/45689286/48023e53-c280-488a-9b99-4b487cee5d6b)

**Comment by okhentai** [comment]
no need: Our Features, Experience flow, Our Community, FAQ, Read more
Else {
  Copy
  };

**Comment by TaQuangKhoi** [comment]
@okhentai Oke nhé ông

**Comment by TaQuangKhoi** [comment]
@okhentai Làm xong cái này thì cập nhật Status trên project đi
