### ISSUE TITLE
Nghiệp vụ app cho Người thuê

### ISSUE THREAD

**Issue by TaQuangKhoi** [TaQuangKhoi/Bao-Cao-Web-3#16]
- [ ] Chuyển các nội dung thành từng issue riêng

**Comment by TaQuangKhoi** [comment]
@tamvtok321 Ông có thể dóng issue này nếu ông điền trong file Word rồi

**Comment by tamvtok321** [comment]
Nghiệp vụ cho người thuê, tính ở giai đoạn từ trang Home vào, thì người dùng sẽ ấn vào nút Rank Up. Khi đó View của họ sẽ chuyển sang cái View chọn Rank, chọn elo các kiểu để thiết lập yêu cầu, sau khi thiết lập xong yêu cầu thì họ ấn Gửi thôi.
![image](https://github.com/TaQuangKhoi/Bao-Cao-Web-3/assets/73837205/53ef026a-ada9-472b-8abc-830781d1b1be)
Thì Request nó sẽ nằm trong Order
![image](https://github.com/TaQuangKhoi/Bao-Cao-Web-3/assets/73837205/ad71e90b-6b25-4600-b6e8-4f41a2c1446a)
Phần này thì cũng y chang như bên người cày z, nhưng mặc cái là người thuê sẽ k đổi được trạng thái của Request nha, chỉ ng cày mới đc th. Cũng ấn vào ID r vô khung trò chuyện y chang luôn.
