### ISSUE TITLE
Fix phần giap diện bị lỗi trong giao diện uprank

### ISSUE THREAD

**Issue by TaQuangKhoi** [TaQuangKhoi/Bao-Cao-Web-3#18]
https://bao-cao-cuoi-ky-web-3-41e9314b4801.herokuapp.com/up_rank/

![Image](https://github.com/TaQuangKhoi/Bao-Cao-Web-3/assets/45689286/e330f323-25e6-4158-9867-09e0a63c1f2b)

**Comment by okhentai** [comment]
Done
