### ISSUE TITLE
Nghiệp vụ app cho Người Cày

### ISSUE THREAD

**Issue by TaQuangKhoi** [TaQuangKhoi/Bao-Cao-Web-3#24]

**Comment by TaQuangKhoi** [comment]
@tamvtok321 Ông có thể dóng issue này nếu ông điền trong file Word rồi

**Comment by tamvtok321** [comment]
Nghiệp vụ cho người cày chỉ có 1 cái là đợi người thuê gửi yêu cầu cày thuê thì người cày sẽ nhận được cái yêu cầu ở cái View này.
![image](https://github.com/TaQuangKhoi/Bao-Cao-Web-3/assets/73837205/ad71e90b-6b25-4600-b6e8-4f41a2c1446a)
Cái này là View Order của khách hàng, nhưng khi trở thành người cày thì cái View này sẽ chuyển thành View Request chẳng hạn z.
![image](https://github.com/TaQuangKhoi/Bao-Cao-Web-3/assets/73837205/b86c5336-7dd2-41d8-b822-e0528425dd2c)
ở đây theo bro thấy là nó có 7 cái thuộc tính, thì tui bỏ đi cái Item vs Action r, Employee thì phải chuyển thành Customer
Quan trọng là cái ID, khi yêu cầu tới cái ID sẽ được gạch chân, thì mình ấn vào được cái ID nha. Khi ấn vào cái ID thì nó sẽ hiện ra View Giao dịch, cho người thuê và người dùng có thể nhắn tin với nhau.

**Comment by tamvtok321** [comment]
Người cày còn có thể thay đổi Status cho cái yêu cầu nha. Khi Request vừa được gửi tới người cày, nó sẽ hiển thị Status là Chưa thực hiện, thì khi Request đang ở Status Chưa thực hiện thì người cày có thể tương tác với nó bằng cách Chấp nhận hoặc Hủy bỏ.
Trong trường hợp Chấp nhận, thì Request sẽ được chuyển thành Đang thực hiện, khi Request đang ở trạng thái Đang thực hiện thì người cày có thể tương tác với nó bằng cách Tạm dừng hoặc Hoàn thành.
Trong trường hợp Request chuyển thành trạng thái Tạm dừng, thì người dùng có thể tiếp tục tương tác với cái Request là chuyển nó bằng cách ấn Tiếp tục hoặc Hủy bỏ.
Khi người cày ấn Tiếp tục, trạng thái Request sẽ trở lại thành Đang Thực Hiện
Trong trường hợp người cày ấn Hoàn thành, thì Request sẽ được chuyển sang trạng thái Hoàn thành.
Trong trường hợp người cày ấn Hủy bỏ, thì Request sẽ được chuyển sang trạng thái Hủy bỏ.

Cách mà người dùng có thể tương tác để đổi trạng thái cái Request là ấn đúp chuột vào yêu cầu theo như tui làm trong word, còn nếu bro làm cho nó ấn cái khác thì bảo lại tui, để tui sửa lại cái này
