### ISSUE TITLE
Button Mua Ngay go to Up Rank

### ISSUE THREAD

**Issue by TaQuangKhoi** [TaQuangKhoi/Bao-Cao-Web-3#35]
![image](https://github.com/TaQuangKhoi/Bao-Cao-Web-3/assets/45689286/ae2d1bb0-cdfc-467d-841b-37774d4de057)

@NguyenQuangLuan606 Khi nhấn nút Mua Ngay này thì chuyển tới trang up_rank

Cc @tamvtok321

**Comment by tamvtok321** [comment]
khi người dùng ấn vào nút Mua Ngay, màn hình sẽ chuyển sang View để người dùng thiết lập yêu cầu
Link view BoostRoyal: https://boostroyal.com/lol-boosting/
Nút Mua Ngay này chỉ nằm trong trang Dashboard, vì vậy chỉ có thể thấy sau khi người dùng đã đăng nhập.
