### ISSUE TITLE
Logic cho nút Sign Out

### ISSUE THREAD

**Issue by TaQuangKhoi** [TaQuangKhoi/Bao-Cao-Web-3#36]
![image](https://github.com/TaQuangKhoi/Bao-Cao-Web-3/assets/45689286/28c4de72-d7ae-4a03-9332-6f265acb3465)

**Comment by tamvtok321** [comment]
Khi người dùng ấn biểu tượng nút Đăng Xuất, màn hình sẽ tự động lui về trang chủ
Link view Trang chủ BoostRoyal: https://boostroyal.com/
Chức năng này chỉ có thể thấy sau khi người dùng ấn vào icon profile của mình để tiếng vào trang Dashboard vì vậy để sử dụng chức năng này thì người dùng cần thực hiện Đăng Nhập.
