### ISSUE TITLE
Làm phần diagram vào file Word

### ISSUE THREAD

**Issue by TaQuangKhoi** [TaQuangKhoi/Bao-Cao-Web-3#40]
Tải file này về và edit nhé @tien1776 
[Web3_Khoi_Tam_Tam_Luan_Tien_v1.docx](https://github.com/TaQuangKhoi/Bao-Cao-Web-3/files/13378368/Web3_Khoi_Tam_Tam_Luan_Tien_v1.docx)

Cc @tamvtok321

**Comment by tien1776** [comment]
[Web3_Khoi_Tam_Tam_Luan_Tien_v1.docx](https://github.com/TaQuangKhoi/Bao-Cao-Web-3/files/13389753/Web3_Khoi_Tam_Tam_Luan_Tien_v1.docx)
xong Sơ đồ Quan hệ thực thể với sơ đồ thực thể

**Comment by tien1776** [comment]
[Uploading Web3_Khoi_Tam_Tam_Luan_Tien_v2.docx…]()

**Comment by tamvtok321** [comment]
oke r đó, giờ tí chụp mấy cái giao diện vô word nữa là xong
