### ISSUE TITLE
Nút để chuyển đến trang Sign In từ trang Home

### ISSUE THREAD

**Issue by TaQuangKhoi** [TaQuangKhoi/Bao-Cao-Web-3#52]

**Comment by tamvtok321** [comment]
![image](https://github.com/TaQuangKhoi/Bao-Cao-Web-3/assets/73837205/c4d0f369-cbcd-46d4-90cc-b7f640c8858a)
Trên header của trang Home có cái icon người ở bên phải á 
![image](https://github.com/TaQuangKhoi/Bao-Cao-Web-3/assets/73837205/4d081bc4-87f0-4f2b-b17d-bc6aaa9bb822)
chỉ cần ấn vào đó là trang đăng nhập hiện lên, bro cho nó chuyển trang hay pop-up đều được hết nha.
