### ISSUE TITLE
Chụp giao diện vào Báo Cáo

### ISSUE THREAD

**Issue by TaQuangKhoi** [TaQuangKhoi/Bao-Cao-Web-3#82]

**Comment by tamvtok321** [comment]
[Web3_Khoi_Tam_Tam_Luan_Tien_v3.docx](https://github.com/TaQuangKhoi/Bao-Cao-Web-3/files/13391291/Web3_Khoi_Tam_Tam_Luan_Tien_v3.docx)

Báo cáo sau khi đã chụp View lên, thêm Caption cho hình ảnh và bảng, thêm mục lục.
